#!/bin/bash

PORT=8181
CMD="sphinx-autobuild /doc /doc/_build/html -p ${PORT} -H 0.0.0.0"

docker run -it --rm  \
    --name docs \
    -p ${PORT}:${PORT} \
    -v ${PWD}:/doc \
    sphinx-doc ${CMD}
