#!/bin/bash

PORT=5500
CMD="guard -i -p"

docker run -it --rm  \
    --name sphinx-doc-server \
    -e "PORT=${PORT}" \
    -p ${PORT}:${PORT} \
    -v ${PWD}:/doc \
    -w /doc \
    sphinx-doc ${CMD}
